version: "3"

services:
  postgres:
    image: postgres
    container_name: portfolio-postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: portfolio
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

  postgres-test:
    image: postgres
    container_name: portfolio-postgres-test
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: portfolio
    ports:
      - "5433:5432"
